"use client";

import React, { createContext, useCallback, useContext, useEffect, useMemo, useState, useLayoutEffect } from "react";

export type UiLanguage = "ru" | "en" | "ko";
export type UiTheme = "light" | "dark";

type UiContextValue = {
  language: UiLanguage;
  setLanguage: (language: UiLanguage) => void;
  theme: UiTheme;
  setTheme: (theme: UiTheme) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const UiContext = createContext<UiContextValue | null>(null);

const translations: Record<UiLanguage, Record<string, string>> = {
  ru: {
    "app.title": "Очередь на стирку",
    "header.signedInAs": "Вы вошли как",
    "header.room": "Комната",
    "header.leader": "Лидер",
    "nav.main": "Главная",
    "nav.history": "История",
    "nav.cleanup": "Уборка",
    "nav.students": "Студенты",
    "nav.settings": "Настройки",
    "machine.status": "Статус машины",
    "machine.available": "Свободна",
    "machine.busy": "Занята",
    "machine.washing": "Стирает",
    "machine.ends": "Окончание",
    "machine.current": "Стирает",
    "settings.account": "Аккаунт",
    "settings.logout": "Выйти из аккаунта",
    "settings.language": "Язык",
    "settings.theme": "Тема",
    "settings.theme.light": "Светлая",
    "settings.theme.dark": "Ночная",
    "settings.language.ru": "Русский",
    "settings.language.en": "English",
    "settings.language.ko": "한국어",
    "telegram.connected": "Telegram подключён",
    "telegram.connectedHint": "Уведомления будут приходить в Telegram.",
    "telegram.reconnect": "Переподключить другой Telegram",
    "telegram.connectTitle": "Подключите Telegram",
    "telegram.connectButton": "Подключить Telegram",
    "telegram.connectHint": "После подключения бот автоматически привяжет ваш Telegram.",
    "telegram.bannerTitle": "Подключите Telegram",
    "telegram.bannerSubtitle": "Чтобы получать уведомления, подключите Telegram в настройках.",
    "telegram.bannerButton": "Перейти в настройки",
    "telegram.bannerLater": "Позже",
    "telegram.bannerBody": "Получайте уведомления когда вас позовут за ключом.",
    "auth.title": "Очередь на стирку",
    "auth.subtitle": "Выберите себя из списка",
    "auth.searchPlaceholder": "Поиск по имени или комнате...",
    "auth.notFound": "Ничего не найдено",
    "auth.back": "Назад",
    "auth.enter": "Вход",
    "auth.firstTime": "Первый раз?",
    "auth.enterPassword": "Введите ваш пароль",
    "auth.createPassword": "Придумайте пароль для регистрации",
    "auth.password": "Пароль",
    "auth.show": "Показать",
    "auth.hide": "Скрыть",
    "auth.minChars": "От 6 символов",
    "auth.login": "Войти",
    "auth.register": "Зарегистрироваться",
    "auth.passwordRequired": "Введите пароль",
    "auth.passwordMin": "Пароль должен быть минимум 6 символов",
    "auth.invalidPassword": "Неправильный пароль",
    "auth.registrationError": "Ошибка регистрации",
    "auth.new": "Новый",
    "ban.notice": "Вы забанены. Причина: {{reason}}. Обратитесь к администратору.",
    "ban.reasonUnknown": "Не указана",
    "alert.returnTitle": "Принесите ключ",
    "alert.returnSubtitle": "Подойдите к администратору в комнату {{room}}",
    "alert.returnHint": "После возврата отметьтесь у администратора.",
    "alert.callTitle": "Вас вызывают",
    "alert.callSubtitle": "Подойдите в комнату {{room}}",
    "alert.callHint": "Возьмите оплату за стирку",
    "queue.leave": "Покинуть очередь",
    "queue.joinTitle": "Встать в очередь",
    "queue.nameLabel": "Имя",
    "queue.roomLabel": "Комната",
    "queue.roomUnknown": "Не указана",
    "queue.dateLabel": "Дата стирки",
    "queue.dateNote": "Выберите дату в ближайшие 7 дней.",
    "queue.dateToday": "Сегодня",
    "queue.dateTomorrow": "Завтра",
    "queue.washCount": "Количество стирок",
    "queue.couponsLabel": "Купоны",
    "queue.availableCoupons": "Доступно купонов: {{available}} (активных: {{active}})",
    "queue.noEligibleCoupons": "Нет доступных купонов на выбранную дату.",
    "queue.couponLimit": "Можно выбрать до {{count}} купонов.",
    "queue.paymentCoupons": "Оплата купонами",
    "queue.paymentCouponsMoney": "Купоны + деньги",
    "queue.paymentMoney": "Оплата деньгами",
    "queue.submitting": "Добавление...",
    "queue.submit": "Встать в очередь",
    "queue.inQueue": "Вы в очереди!",
    "queue.position": "Позиция #{{position}}",
    "queue.scheduledFor": "Запланировано на: {{date}}",
    "queue.couponsUsedLabel": "Купоны:",
    "queue.submitError": "Не удалось встать в очередь.",
    "coupon.permanent": "Бессрочный",
    "coupon.until": "До: {{date}}",
    "coupon.optionPermanent": "Купон бессрочный",
    "coupon.optionUntil": "Купон до {{date}}",
    "studentActions.noticeSent": "Уведомление отправлено",
    "studentActions.startTitle": "Можно начинать стирку",
    "studentActions.startHint": "Нажмите кнопку, чтобы сообщить администратору о начале стирки.",
    "studentActions.startInfo": "Уведомление отправится в Telegram.",
    "studentActions.startButton": "Начать стирку",
    "studentActions.washingTitle": "Стирка идет",
    "studentActions.elapsedLabel": "Прошло времени:",
    "studentActions.finishHint": "После окончания нажмите кнопку, чтобы уведомить администратора.",
    "studentActions.finishButton": "Закончить стирку",
    "time.closed": "Стирка сейчас закрыта. Запись откроется в {{openHour}}:00.",
    "time.warning": "До закрытия осталось: {{time}}. Успейте завершить стирку до {{closeHour}}:00!",
    "time.closedHint": "Записаться в очередь можно после {{openHour}}:00.",
    "errors.supabaseNotConfigured": "Supabase не настроен",
    "errors.noActiveSession": "Нет активной сессии",
    "errors.notifyFailed": "Ошибка отправки уведомления",
    "errors.generic": "Ошибка: {{message}}",
    "common.loading": "Загрузка...",
    "common.scrollTop": "Прокрутить вверх",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.deleteConfirm": "Удалить {{name}}?",
    "history.title": "История",
    "history.emptyTitle": "История пуста",
    "history.emptyHint": "Записей о стирках пока нет.",
    "history.total": "Всего стирок: {{count}}",
    "history.clear": "Очистка истории",
    "history.clearHide": "Скрыть очистку",
    "history.clearRange": "Очистить выборочно",
    "history.clearAll": "Очистить всё",
    "history.clearRangeMissing": "Укажите период или комнату для выборочной очистки.",
    "history.clearConfirmAll": "Очистить всю историю стирок?",
    "history.clearConfirmRange": "Очистить выбранные записи истории?",
    "history.clearError": "Ошибка очистки истории",
    "history.clearDeleted": "Удалено записей: {{count}}",
    "history.deleteConfirm": "Удалить эту запись истории?",
    "history.deleteError": "Ошибка удаления записи",
    "history.deleteSuccess": "Удалено ✅",
    "history.deleteErrorAlert": "Ошибка: {{message}} ✅",
    "history.from": "С",
    "history.to": "По",
    "history.room": "Комната",
    "history.roomPlaceholder": "Например A301",
    "history.delete": "Удалить",
    "history.washStart": "Начало стирки",
    "history.washEnd": "Конец стирки",
    "history.totalTime": "Общее время",
    "history.washCount": "Количество стирок",
    "history.payment": "Оплата",
    "history.keyIssued": "Ключ был выдан",
    "history.keyReturned": "Ключ возвращался",
    "history.keyFetch": "Шёл за ключом",
    "history.washing": "Стирал",
    "history.loadMore": "Загрузить ещё 50",
    "history.loadingMore": "Загрузка...",
    "payment.coupons": "Купоны: {{count}}",
    "payment.couponsMoney": "Купоны: {{count}} + деньги",
    "payment.coupon": "Купон",
    "payment.couponMoney": "Купон + деньги",
    "payment.money": "Деньги",
    "students.title": "Список студентов",
    "students.empty": "Студенты пока не найдены.",
    "students.add": "Добавить студента",
    "students.blockA": "Блок A",
    "students.blockB": "Блок B",
    "students.name": "Имя",
    "students.room": "Комната",
    "students.telegram": "Telegram",
    "students.actions": "Действия",
    "students.edit": "Редактировать",
    "students.editTitle": "Редактирование студента",
    "students.notConnected": "Не подключен",
    "students.connected": "Подключен",
    "students.keyNone": "Ключа нет",
    "students.keyIssued": "Ключ выдан",
    "students.keyLost": "Ключ потерян",
    "students.updateSuccess": "Студент обновлён ✅",
    "students.updateError": "Ошибка обновления студента",
    "students.deleteSuccess": "Студент удалён ✅",
    "students.deleteError": "Ошибка удаления студента",
    "students.deleteConfirm": "Удалить {{name}}?",
    "students.delete": "Удалить",
    "students.listOpen": "Список открыт",
    "students.listClosed": "Список закрыт",
    "students.listOpenShort": "Открыт",
    "students.listClosedShort": "Закрыт",
    "students.canView": "Доступ к списку студентов",
    "students.field.firstName": "Имя",
    "students.field.lastName": "Фамилия",
    "students.field.middleName": "Отчество",
    "students.field.room": "Комната",
    "students.field.firstNamePlaceholder": "Например Павел",
    "students.field.lastNamePlaceholder": "Например Иванов",
    "students.field.middleNamePlaceholder": "Отчество (необязательно)",
    "students.field.roomPlaceholder": "A301 или B402",
    "students.addTitle": "Добавить студента",
    "students.addSubmit": "Добавить",
    "students.addSubmitting": "Добавление...",
    "students.addMissingFirstName": "Укажите имя",
    "students.addMissingLastName": "Укажите фамилию",
    "students.addRoomRequired": "Укажите комнату",
    "students.addRoomFormat": "Формат комнаты: A301 или B402",
    "students.addRoomRange": "Диапазон комнат: 101-999",
    "students.addRoomHint": "Только блоки A и B, номера 101-999 (например: A301, B402)",
    "students.addSuccess": "Студент добавлен",
    "students.addDuplicate": "Студент с таким ФИО и комнатой уже существует",
    "students.addError": "Ошибка добавления: {{message}}",
    "students.addErrorFallback": "Неизвестная ошибка",
    "admin.loginRequiredTitle": "Требуется вход",
    "admin.loginRequiredBody": "Сначала войдите как студент с правами администратора, затем введите админ-ключ.",
    "admin.loginRequiredHint": "Это нужно для корректной работы с базой и политиками безопасности.",
    "admin.loginPromptTitle": "Администратор",
    "admin.loginPromptBody": "Войдите как студент с правами администратора для доступа к панели.",
    "admin.panelTitle": "Панель администратора",
    "admin.panelModeSuper": "Режим суперадмина",
    "admin.panelModeAdmin": "Режим администратора",
    "admin.studentsToggleShow": "Управление студентами",
    "admin.studentsToggleHide": "Скрыть студентов",
    "admin.studentsCount": "Студенты ({{count}})",
    "admin.addStudent": "Добавить студента",
    "admin.searchPlaceholder": "Поиск по имени или комнате",
    "admin.filter.all": "Все",
    "admin.filter.registered": "Зарег.",
    "admin.filter.unregistered": "Не зар.",
    "admin.filter.banned": "Баны",
    "admin.roomMissing": "Нет",
    "admin.status.registered": "Зарегистрирован",
    "admin.status.unregistered": "Не зарегистрирован",
    "admin.status.banned": "Заблокирован",
    "admin.status.admin": "Админ",
    "admin.status.superAdmin": "Суперадмин",
    "admin.status.leader": "Лидер",
    "admin.editTitle": "Редактировать студента",
    "admin.resetTitle": "Сбросить регистрацию?",
    "admin.resetConfirm": "Сбросить регистрацию для {{name}}.",
    "admin.resetHint": "Студент сможет зарегистрироваться заново.",
    "admin.resetAction": "Сбросить",
    "admin.banTitle": "Забанить студента",
    "admin.banConfirm": "Забанить {{name}}.",
    "admin.banPlaceholder": "Причина бана (опционально)",
    "admin.banAction": "Забанить",
    "admin.deleteTitle": "Удалить студента?",
    "admin.deleteConfirm": "Вы уверены, что хотите удалить {{name}}?",
    "admin.deleteHint": "Это действие нельзя отменить. Будут удалены все данные студента.",
    "admin.deleteAction": "Удалить",
    "admin.addQueueTitle": "Поставить в очередь",
    "admin.addQueueStudent": "Студент",
    "admin.addQueueDate": "Дата стирки",
    "admin.addQueueWashCount": "Количество стирок",
    "admin.addQueueCoupons": "Купоны",
    "admin.addQueueHint": "Проверка доступных купонов выполнится при добавлении.",
    "admin.addQueueAction": "Добавить",
    "admin.close": "Закрыть",
    "admin.resetSuccess": "Регистрация сброшена",
    "admin.resetError": "Ошибка сброса регистрации",
    "admin.banSuccess": "Студент забанен",
    "admin.unbanSuccess": "Студент разбанен",
    "admin.deleteSuccess": "Студент удален",
    "admin.addQueueSuccess": "Студент добавлен в очередь",
    "admin.toggleAdminGranted": "Назначен администратором",
    "admin.toggleAdminRevoked": "Права администратора сняты",
    "admin.error": "Ошибка: {{message}}",
    "admin.actions.manage": "Управление",
    "admin.actions.noName": "Без имени",
    "admin.actions.roomLabel": "Комната {{room}}",
    "admin.actions.roomMissing": "Комната не указана",
    "admin.badge.superAdmin": "Суперадмин",
    "admin.badge.admin": "Админ",
    "admin.badge.leader": "Лидер",
    "admin.badge.registered": "Зарегистрирован",
    "admin.badge.banned": "Забанен",
    "admin.section.queue": "Очередь",
    "admin.section.account": "Учётная запись",
    "admin.section.rights": "Права доступа",
    "admin.section.danger": "Опасная зона",
    "admin.action.queueAdd": "Поставить в очередь",
    "admin.action.editProfile": "Редактировать профиль",
    "admin.action.resetRegistration": "Сбросить регистрацию",
    "admin.action.ban": "Забанить",
    "admin.action.unban": "Разбанить",
    "admin.action.makeAdmin": "Сделать админом",
    "admin.action.removeAdmin": "Снять права админа",
    "admin.action.deleteStudent": "Удалить студента",
    "cleanup.title": "Результаты уборки",
    "cleanup.subtitle": "Объявления по блокам и архив",
    "cleanup.toHome": "На главную",
    "cleanup.empty": "Результатов пока нет.",
    "password.title": "Изменение пароля",
    "password.current": "Текущий пароль",
    "password.new": "Новый пароль",
    "password.confirm": "Подтвердите новый пароль",
    "password.placeholderCurrent": "Введите текущий пароль",
    "password.placeholderNew": "Введите новый пароль",
    "password.placeholderConfirm": "Повторите пароль",
    "password.minHint": "Минимум 6 символов",
    "password.update": "Изменить пароль",
    "password.updating": "Изменение...",
    "password.errorRequired": "Заполните все поля",
    "password.errorMin": "Пароль должен быть не короче 6 символов",
    "password.errorMismatch": "Пароли не совпадают",
    "password.errorSame": "Новый пароль должен отличаться от текущего",
    "password.errorAuthMissing": "auth_email отсутствует",
    "password.errorCurrentInvalid": "Неверный текущий пароль",
    "password.errorUpdate": "Ошибка смены пароля",
    "password.success": "Пароль успешно изменен",
    "avatar.title": "Выбор стиля аватара",
    "avatar.previewLabel": "Превью вашего аватара:",
    "avatar.currentStyleLabel": "Стиль:",
    "avatar.save": "Сохранить",
    "avatar.saving": "Сохранение...",
    "avatar.random": "Выбрать случайный аватар",
    "avatar.chooseStyle": "Выберите стиль:",
    "avatar.saved": "Аватар сохранён!",
    "avatar.saveError": "Ошибка сохранения аватара",
    "avatar.style.avataaars.desc": "Классические аватары с волосами и одеждой",
    "avatar.style.lorelei.desc": "Женские аватары",
    "avatar.style.pixel-art.desc": "Пиксельный стиль",
    "avatar.style.adventurer.desc": "Приключенческий стиль",
    "avatar.style.big-ears.desc": "С большими ушами",
    "avatar.style.bottts.desc": "Роботы",
    "avatar.style.croodles.desc": "Каракули",
    "avatar.style.micah.desc": "Минималистичный стиль",
    "avatar.style.miniavs.desc": "Мини-аватары",
    "avatar.style.notionists.desc": "Стиль Notion",
    "avatar.style.personas.desc": "Персонажи",
    "avatar.style.thumbs.desc": "В стиле thumbs",
    "avatar.style.fun-emoji.desc": "Весёлые эмодзи",
    "queue.searchPlaceholder": "Поиск по имени или комнате..."
  },
  en: {
    "app.title": "Laundry Queue",
    "header.signedInAs": "Signed in as",
    "header.room": "Room",
    "header.leader": "Leader",
    "nav.main": "Home",
    "nav.history": "History",
    "nav.cleanup": "Cleanup",
    "nav.students": "Students",
    "nav.settings": "Settings",
    "machine.status": "Machine Status",
    "machine.available": "Available",
    "machine.busy": "In use",
    "machine.washing": "Washing",
    "machine.ends": "Finish",
    "machine.current": "Washing",
    "settings.account": "Account",
    "settings.logout": "Log out",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Night",
    "settings.language.ru": "Russian",
    "settings.language.en": "English",
    "settings.language.ko": "Korean",
    "telegram.connected": "Telegram connected",
    "telegram.connectedHint": "Notifications will arrive in Telegram.",
    "telegram.reconnect": "Reconnect another Telegram",
    "telegram.connectTitle": "Connect Telegram",
    "telegram.connectButton": "Connect Telegram",
    "telegram.connectHint": "After connecting, the bot will link your Telegram automatically.",
    "telegram.bannerTitle": "Connect Telegram",
    "telegram.bannerSubtitle": "To receive notifications, connect Telegram in settings.",
    "telegram.bannerButton": "Go to settings",
    "telegram.bannerLater": "Later",
    "telegram.bannerBody": "Get notifications when you are called to pick up the key.",
    "auth.title": "Laundry Queue",
    "auth.subtitle": "Choose yourself from the list",
    "auth.searchPlaceholder": "Search by name or room...",
    "auth.notFound": "Nothing found",
    "auth.back": "Back",
    "auth.enter": "Sign in",
    "auth.firstTime": "First time?",
    "auth.enterPassword": "Enter your password",
    "auth.createPassword": "Create a password to register",
    "auth.password": "Password",
    "auth.show": "Show",
    "auth.hide": "Hide",
    "auth.minChars": "At least 6 characters",
    "auth.login": "Sign in",
    "auth.register": "Register",
    "auth.passwordRequired": "Enter your password",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.invalidPassword": "Incorrect password",
    "auth.registrationError": "Registration error",
    "auth.new": "New",
    "ban.notice": "You are banned. Reason: {{reason}}. Contact the administrator.",
    "ban.reasonUnknown": "Not specified",
    "alert.returnTitle": "Return the key",
    "alert.returnSubtitle": "Please go to room {{room}}",
    "alert.returnHint": "Check in with the admin after returning.",
    "alert.callTitle": "You are called",
    "alert.callSubtitle": "Please go to room {{room}}",
    "alert.callHint": "Bring payment for the wash",
    "queue.leave": "Leave queue",
    "queue.joinTitle": "Join the queue",
    "queue.nameLabel": "Name",
    "queue.roomLabel": "Room",
    "queue.roomUnknown": "Not specified",
    "queue.dateLabel": "Wash date",
    "queue.dateNote": "Choose a date within the next 7 days.",
    "queue.dateToday": "Today",
    "queue.dateTomorrow": "Tomorrow",
    "queue.washCount": "Wash count",
    "queue.couponsLabel": "Coupons",
    "queue.availableCoupons": "Available coupons: {{available}} (active: {{active}})",
    "queue.noEligibleCoupons": "No available coupons for the selected date.",
    "queue.couponLimit": "You can select up to {{count}} coupons.",
    "queue.paymentCoupons": "Pay with coupons",
    "queue.paymentCouponsMoney": "Coupons + money",
    "queue.paymentMoney": "Pay with cash",
    "queue.submitting": "Adding...",
    "queue.submit": "Join the queue",
    "queue.inQueue": "You are in the queue!",
    "queue.position": "Position #{{position}}",
    "queue.scheduledFor": "Scheduled for: {{date}}",
    "queue.couponsUsedLabel": "Coupons:",
    "queue.submitError": "Failed to join the queue.",
    "coupon.permanent": "Permanent",
    "coupon.until": "Until: {{date}}",
    "coupon.optionPermanent": "Permanent coupon",
    "coupon.optionUntil": "Coupon until {{date}}",
    "studentActions.noticeSent": "Notification sent",
    "studentActions.startTitle": "You can start washing",
    "studentActions.startHint": "Press the button to notify the admin that you started.",
    "studentActions.startInfo": "A Telegram notification will be sent.",
    "studentActions.startButton": "Start washing",
    "studentActions.washingTitle": "Washing in progress",
    "studentActions.elapsedLabel": "Elapsed time:",
    "studentActions.finishHint": "When done, press the button to notify the admin.",
    "studentActions.finishButton": "Finish washing",
    "time.closed": "Laundry is closed right now. Registration opens at {{openHour}}:00.",
    "time.warning": "Time until close: {{time}}. Please finish before {{closeHour}}:00.",
    "time.closedHint": "You can join the queue after {{openHour}}:00.",
    "errors.supabaseNotConfigured": "Supabase is not configured",
    "errors.noActiveSession": "No active session",
    "errors.notifyFailed": "Failed to send notification",
    "errors.generic": "Error: {{message}}",
    "common.loading": "Loading...",
    "common.scrollTop": "Scroll to top",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.deleteConfirm": "Delete {{name}}?",
    "history.title": "History",
    "history.emptyTitle": "History is empty",
    "history.emptyHint": "No wash records yet.",
    "history.total": "Total washes: {{count}}",
    "history.clear": "Clear history",
    "history.clearHide": "Hide cleanup",
    "history.clearRange": "Clear selected",
    "history.clearAll": "Clear all",
    "history.clearRangeMissing": "Specify a date range or room for selective cleanup.",
    "history.clearConfirmAll": "Clear all wash history?",
    "history.clearConfirmRange": "Clear selected history entries?",
    "history.clearError": "History cleanup error",
    "history.clearDeleted": "Deleted records: {{count}}",
    "history.deleteConfirm": "Delete this history entry?",
    "history.deleteError": "Error deleting entry",
    "history.deleteSuccess": "Deleted ",
    "history.deleteErrorAlert": "Error: {{message}} ",
    "history.from": "From",
    "history.to": "To",
    "history.room": "Room",
    "history.roomPlaceholder": "e.g. A301",
    "history.delete": "Delete",
    "history.washStart": "Wash start",
    "history.washEnd": "Wash end",
    "history.totalTime": "Total time",
    "history.washCount": "Wash count",
    "history.payment": "Payment",
    "history.keyIssued": "Key was issued",
    "history.keyReturned": "Key returned",
    "history.keyFetch": "Went for key",
    "history.washing": "Was washing",
    "history.loadMore": "Load 50 more",
    "history.loadingMore": "Loading...",
    "payment.coupons": "Coupons: {{count}}",
    "payment.couponsMoney": "Coupons: {{count}} + money",
    "payment.coupon": "Coupon",
    "payment.couponMoney": "Coupon + money",
    "payment.money": "Money",
    "students.title": "Students list",
    "students.empty": "No students found yet.",
    "students.add": "Add student",
    "students.blockA": "Block A",
    "students.blockB": "Block B",
    "students.name": "Name",
    "students.room": "Room",
    "students.telegram": "Telegram",
    "students.actions": "Actions",
    "students.edit": "Edit",
    "students.editTitle": "Edit student",
    "students.notConnected": "Not connected",
    "students.connected": "Connected",
    "students.keyNone": "No key",
    "students.keyIssued": "Key issued",
    "students.keyLost": "Key lost",
    "students.updateSuccess": "Student updated ",
    "students.updateError": "Failed to update student",
    "students.deleteSuccess": "Student deleted ",
    "students.deleteError": "Failed to delete student",
    "students.deleteConfirm": "Delete {{name}}?",
    "students.delete": "Delete",
    "students.listOpen": "List open",
    "students.listClosed": "List closed",
    "students.listOpenShort": "Open",
    "students.listClosedShort": "Closed",
    "students.canView": "Can view students list",
    "students.field.firstName": "First name",
    "students.field.lastName": "Last name",
    "students.field.middleName": "Middle name",
    "students.field.room": "Room",
    "students.field.firstNamePlaceholder": "e.g. Pavel",
    "students.field.lastNamePlaceholder": "e.g. Ivanov",
    "students.field.middleNamePlaceholder": "Middle name (optional)",
    "students.field.roomPlaceholder": "A301 or B402",
    "students.addTitle": "Add student",
    "students.addSubmit": "Add",
    "students.addSubmitting": "Adding...",
    "students.addMissingFirstName": "Enter first name",
    "students.addMissingLastName": "Enter last name",
    "students.addRoomRequired": "Enter room",
    "students.addRoomFormat": "Room format: A301 or B402",
    "students.addRoomRange": "Room range: 101-999",
    "students.addRoomHint": "Only blocks A and B, rooms 101-999 (e.g. A301, B402)",
    "students.addSuccess": "Student added",
    "students.addDuplicate": "Student with this name and room already exists",
    "students.addError": "Add failed: {{message}}",
    "students.addErrorFallback": "Unknown error",
    "admin.loginRequiredTitle": "Sign in required",
    "admin.loginRequiredBody": "First sign in as a student with admin rights, then enter the admin key.",
    "admin.loginRequiredHint": "This is required for secure database access.",
    "admin.loginPromptTitle": "Administrator",
    "admin.loginPromptBody": "Sign in as a student with admin rights to access the panel.",
    "admin.panelTitle": "Admin panel",
    "admin.panelModeSuper": "Super admin mode",
    "admin.panelModeAdmin": "Admin mode",
    "admin.studentsToggleShow": "Manage students",
    "admin.studentsToggleHide": "Hide students",
    "admin.studentsCount": "Students ({{count}})",
    "admin.addStudent": "Add student",
    "admin.searchPlaceholder": "Search by name or room",
    "admin.filter.all": "All",
    "admin.filter.registered": "Reg.",
    "admin.filter.unregistered": "Not reg.",
    "admin.filter.banned": "Banned",
    "admin.roomMissing": "None",
    "admin.status.registered": "Registered",
    "admin.status.unregistered": "Not registered",
    "admin.status.banned": "Banned",
    "admin.status.admin": "Admin",
    "admin.status.superAdmin": "Super admin",
    "admin.status.leader": "Leader",
    "admin.editTitle": "Edit student",
    "admin.resetTitle": "Reset registration?",
    "admin.resetConfirm": "Reset registration for {{name}}.",
    "admin.resetHint": "The student will be able to register again.",
    "admin.resetAction": "Reset",
    "admin.banTitle": "Ban student",
    "admin.banConfirm": "Ban {{name}}.",
    "admin.banPlaceholder": "Ban reason (optional)",
    "admin.banAction": "Ban",
    "admin.deleteTitle": "Delete student?",
    "admin.deleteConfirm": "Are you sure you want to delete {{name}}?",
    "admin.deleteHint": "This action cannot be undone. All student data will be removed.",
    "admin.deleteAction": "Delete",
    "admin.addQueueTitle": "Add to queue",
    "admin.addQueueStudent": "Student",
    "admin.addQueueDate": "Wash date",
    "admin.addQueueWashCount": "Wash count",
    "admin.addQueueCoupons": "Coupons",
    "admin.addQueueHint": "Available coupons will be checked on add.",
    "admin.addQueueAction": "Add",
    "admin.close": "Close",
    "admin.resetSuccess": "Registration reset",
    "admin.resetError": "Reset failed",
    "admin.banSuccess": "Student banned",
    "admin.unbanSuccess": "Student unbanned",
    "admin.deleteSuccess": "Student deleted",
    "admin.addQueueSuccess": "Student added to queue",
    "admin.toggleAdminGranted": "Admin rights granted",
    "admin.toggleAdminRevoked": "Admin rights removed",
    "admin.error": "Error: {{message}}",
    "admin.actions.manage": "Manage",
    "admin.actions.noName": "No name",
    "admin.actions.roomLabel": "Room {{room}}",
    "admin.actions.roomMissing": "Room not set",
    "admin.badge.superAdmin": "Super admin",
    "admin.badge.admin": "Admin",
    "admin.badge.leader": "Leader",
    "admin.badge.registered": "Registered",
    "admin.badge.banned": "Banned",
    "admin.section.queue": "Queue",
    "admin.section.account": "Account",
    "admin.section.rights": "Access rights",
    "admin.section.danger": "Danger zone",
    "admin.action.queueAdd": "Add to queue",
    "admin.action.editProfile": "Edit profile",
    "admin.action.resetRegistration": "Reset registration",
    "admin.action.ban": "Ban",
    "admin.action.unban": "Unban",
    "admin.action.makeAdmin": "Make admin",
    "admin.action.removeAdmin": "Remove admin rights",
    "admin.action.deleteStudent": "Delete student",
    "cleanup.title": "Cleanup results",
    "cleanup.subtitle": "Block announcements and archive",
    "cleanup.toHome": "Back to home",
    "cleanup.empty": "No results yet.",
    "password.title": "Change password",
    "password.current": "Current password",
    "password.new": "New password",
    "password.confirm": "Confirm new password",
    "password.placeholderCurrent": "Enter current password",
    "password.placeholderNew": "Enter new password",
    "password.placeholderConfirm": "Repeat password",
    "password.minHint": "Minimum 6 characters",
    "password.update": "Change password",
    "password.updating": "Updating...",
    "password.errorRequired": "Fill in all fields",
    "password.errorMin": "Password must be at least 6 characters",
    "password.errorMismatch": "Passwords do not match",
    "password.errorSame": "New password must differ from current",
    "password.errorAuthMissing": "auth_email is missing",
    "password.errorCurrentInvalid": "Incorrect current password",
    "password.errorUpdate": "Password change error",
    "password.success": "Password updated",
    "avatar.title": "Choose avatar style",
    "avatar.previewLabel": "Avatar preview:",
    "avatar.currentStyleLabel": "Style:",
    "avatar.save": "Save",
    "avatar.saving": "Saving...",
    "avatar.random": "Random avatar",
    "avatar.chooseStyle": "Choose a style:",
    "avatar.saved": "Avatar saved!",
    "avatar.saveError": "Failed to save avatar",
    "avatar.style.avataaars.desc": "Classic avatars with hair and outfits",
    "avatar.style.lorelei.desc": "Feminine avatars",
    "avatar.style.pixel-art.desc": "Pixel art style",
    "avatar.style.adventurer.desc": "Adventurer style",
    "avatar.style.big-ears.desc": "Big ears style",
    "avatar.style.bottts.desc": "Robots",
    "avatar.style.croodles.desc": "Scribble style",
    "avatar.style.micah.desc": "Minimal style",
    "avatar.style.miniavs.desc": "Mini avatars",
    "avatar.style.notionists.desc": "Notion style",
    "avatar.style.personas.desc": "Personas",
    "avatar.style.thumbs.desc": "Thumbs style",
    "avatar.style.fun-emoji.desc": "Fun emojis",
    "queue.searchPlaceholder": "Search by name or room..."
  },
  ko: {
    "app.title": "세탁 대기열",
    "header.signedInAs": "로그인:",
    "header.room": "방",
    "header.leader": "리더",
    "nav.main": "홈",
    "nav.history": "기록",
    "nav.cleanup": "청소",
    "nav.students": "학생",
    "nav.settings": "설정",
    "machine.status": "세탁기 상태",
    "machine.available": "사용 가능",
    "machine.busy": "사용 중",
    "machine.washing": "세탁 중",
    "machine.ends": "종료 시간",
    "machine.current": "세탁 중",
    "settings.account": "계정",
    "settings.logout": "로그아웃",
    "settings.language": "언어",
    "settings.theme": "테마",
    "settings.theme.light": "라이트",
    "settings.theme.dark": "나이트",
    "settings.language.ru": "러시아어",
    "settings.language.en": "영어",
    "settings.language.ko": "한국어",
    "telegram.connected": "Telegram 연결됨",
    "telegram.connectedHint": "알림이 Telegram으로 전송됩니다.",
    "telegram.reconnect": "다른 Telegram 다시 연결",
    "telegram.connectTitle": "Telegram 연결",
    "telegram.connectButton": "Telegram 연결하기",
    "telegram.connectHint": "연결하면 봇이 Telegram을 자동으로 연동합니다.",
    "telegram.bannerTitle": "Telegram 연결",
    "telegram.bannerSubtitle": "알림을 받으려면 설정에서 Telegram을 연결하세요.",
    "telegram.bannerButton": "설정으로 이동",
    "telegram.bannerLater": "나중에",
    "telegram.bannerBody": "열쇠 호출 알림을 Telegram으로 받으세요.",
    "auth.title": "세탁 대기열",
    "auth.subtitle": "목록에서 본인을 선택하세요",
    "auth.searchPlaceholder": "이름 또는 방으로 검색...",
    "auth.notFound": "검색 결과 없음",
    "auth.back": "뒤로",
    "auth.enter": "로그인",
    "auth.firstTime": "처음이신가요?",
    "auth.enterPassword": "비밀번호를 입력하세요",
    "auth.createPassword": "가입을 위한 비밀번호를 만드세요",
    "auth.password": "비밀번호",
    "auth.show": "보기",
    "auth.hide": "숨기기",
    "auth.minChars": "최소 6자",
    "auth.login": "로그인",
    "auth.register": "가입",
    "auth.passwordRequired": "비밀번호를 입력하세요",
    "auth.passwordMin": "비밀번호는 최소 6자여야 합니다",
    "auth.invalidPassword": "비밀번호가 올바르지 않습니다",
    "auth.registrationError": "가입 오류",
    "auth.new": "신규",
    "ban.notice": "차단되었습니다. 사유: {{reason}}. 관리자에게 문의하세요.",
    "ban.reasonUnknown": "미기재",
    "alert.returnTitle": "열쇠를 가져오세요",
    "alert.returnSubtitle": "{{room}}호 관리자에게 오세요",
    "alert.returnHint": "반납 후 관리자에게 확인하세요.",
    "alert.callTitle": "호출되었습니다",
    "alert.callSubtitle": "{{room}}호로 와주세요",
    "alert.callHint": "세탁비를 준비하세요",
    "queue.leave": "대기열 나가기",
    "queue.joinTitle": "대기열 등록",
    "queue.nameLabel": "이름",
    "queue.roomLabel": "방",
    "queue.roomUnknown": "미기재",
    "queue.dateLabel": "세탁 날짜",
    "queue.dateNote": "7일 이내 날짜를 선택하세요.",
    "queue.dateToday": "오늘",
    "queue.dateTomorrow": "내일",
    "queue.washCount": "세탁 횟수",
    "queue.couponsLabel": "쿠폰",
    "queue.availableCoupons": "사용 가능 쿠폰: {{available}} (활성: {{active}})",
    "queue.noEligibleCoupons": "선택한 날짜에 사용 가능한 쿠폰이 없습니다.",
    "queue.couponLimit": "최대 {{count}}개까지 선택할 수 있습니다.",
    "queue.paymentCoupons": "쿠폰 결제",
    "queue.paymentCouponsMoney": "쿠폰 + 현금",
    "queue.paymentMoney": "현금 결제",
    "queue.submitting": "추가 중...",
    "queue.submit": "대기열 등록",
    "queue.inQueue": "대기열에 등록되었습니다!",
    "queue.position": "순번 #{{position}}",
    "queue.scheduledFor": "예약 날짜: {{date}}",
    "queue.couponsUsedLabel": "쿠폰:",
    "queue.submitError": "대기열 등록에 실패했습니다.",
    "coupon.permanent": "무기한",
    "coupon.until": "까지: {{date}}",
    "coupon.optionPermanent": "무기한 쿠폰",
    "coupon.optionUntil": "{{date}}까지 쿠폰",
    "studentActions.noticeSent": "알림이 전송되었습니다",
    "studentActions.startTitle": "세탁을 시작할 수 있습니다",
    "studentActions.startHint": "버튼을 눌러 관리자에게 시작을 알리세요.",
    "studentActions.startInfo": "Telegram으로 알림이 전송됩니다.",
    "studentActions.startButton": "세탁 시작",
    "studentActions.washingTitle": "세탁 중",
    "studentActions.elapsedLabel": "경과 시간:",
    "studentActions.finishHint": "끝나면 버튼을 눌러 관리자에게 알리세요.",
    "studentActions.finishButton": "세탁 종료",
    "time.closed": "지금 세탁이 종료되었습니다. {{openHour}}:00에 접수됩니다.",
    "time.warning": "마감까지 남은 시간: {{time}}. {{closeHour}}:00 전에 마쳐 주세요!",
    "time.closedHint": "{{openHour}}:00 이후에 대기열 등록이 가능합니다.",
    "errors.supabaseNotConfigured": "Supabase가 설정되지 않았습니다",
    "errors.noActiveSession": "활성 세션이 없습니다",
    "errors.notifyFailed": "알림 전송 실패",
    "errors.generic": "오류: {{message}}",
    "common.loading": "로딩 중...",
    "common.scrollTop": "맨 위로",
    "common.cancel": "취소",
    "common.save": "저장",
    "common.deleteConfirm": "{{name}}을(를) 삭제할까요?",
    "history.title": "기록",
    "history.emptyTitle": "기록이 없습니다",
    "history.emptyHint": "세탁 기록이 아직 없습니다.",
    "history.total": "총 세탁 횟수: {{count}}",
    "history.clear": "기록 삭제",
    "history.clearHide": "삭제 도구 숨기기",
    "history.clearRange": "선택 삭제",
    "history.clearAll": "전체 삭제",
    "history.clearRangeMissing": "기간 또는 방을 지정하세요.",
    "history.clearConfirmAll": "모든 세탁 기록을 삭제할까요?",
    "history.clearConfirmRange": "선택한 기록을 삭제할까요?",
    "history.clearError": "기록 삭제 오류",
    "history.clearDeleted": "삭제된 기록: {{count}}",
    "history.deleteConfirm": "이 기록을 삭제할까요?",
    "history.deleteError": "기록 삭제 오류",
    "history.deleteSuccess": "삭제됨 ",
    "history.deleteErrorAlert": "오류: {{message}} ",
    "history.from": "시작",
    "history.to": "끝",
    "history.room": "방",
    "history.roomPlaceholder": "예: A301",
    "history.delete": "삭제",
    "history.washStart": "세탁 시작",
    "history.washEnd": "세탁 종료",
    "history.totalTime": "전체 시간",
    "history.washCount": "세탁 횟수",
    "history.payment": "결제",
    "history.keyIssued": "열쇠 발급",
    "history.keyReturned": "열쇠 반환",
    "history.keyFetch": "열쇠 받으러 감",
    "history.washing": "세탁 중",
    "history.loadMore": "50개 더 불러오기",
    "history.loadingMore": "로딩 중...",
    "payment.coupons": "쿠폰: {{count}}",
    "payment.couponsMoney": "쿠폰: {{count}} + 현금",
    "payment.coupon": "쿠폰",
    "payment.couponMoney": "쿠폰 + 현금",
    "payment.money": "현금",
    "students.title": "학생 목록",
    "students.empty": "학생이 없습니다.",
    "students.add": "학생 추가",
    "students.blockA": "블록 A",
    "students.blockB": "블록 B",
    "students.name": "이름",
    "students.room": "방",
    "students.telegram": "Telegram",
    "students.actions": "작업",
    "students.edit": "편집",
    "students.editTitle": "학생 편집",
    "students.notConnected": "연결 안 됨",
    "students.connected": "연결됨",
    "students.keyNone": "열쇠 없음",
    "students.keyIssued": "열쇠 발급",
    "students.keyLost": "열쇠 분실",
    "students.updateSuccess": "학생 정보가 업데이트되었습니다 ",
    "students.updateError": "학생 업데이트 오류",
    "students.deleteSuccess": "학생이 삭제되었습니다 ",
    "students.deleteError": "학생 삭제 오류",
    "students.deleteConfirm": "{{name}}을(를) 삭제할까요?",
    "students.delete": "삭제",
    "students.listOpen": "목록 공개",
    "students.listClosed": "목록 비공개",
    "students.listOpenShort": "공개",
    "students.listClosedShort": "비공개",
    "students.canView": "학생 목록 보기",
    "students.field.firstName": "이름",
    "students.field.lastName": "성",
    "students.field.middleName": "중간 이름",
    "students.field.room": "방",
    "students.field.firstNamePlaceholder": "예: Pavel",
    "students.field.lastNamePlaceholder": "예: Ivanov",
    "students.field.middleNamePlaceholder": "중간 이름(선택)",
    "students.field.roomPlaceholder": "A301 또는 B402",
    "students.addTitle": "학생 추가",
    "students.addSubmit": "추가",
    "students.addSubmitting": "추가 중...",
    "students.addMissingFirstName": "이름을 입력하세요",
    "students.addMissingLastName": "성을 입력하세요",
    "students.addRoomRequired": "방을 입력하세요",
    "students.addRoomFormat": "방 형식: A301 또는 B402",
    "students.addRoomRange": "방 번호: 101-999",
    "students.addRoomHint": "A/B 블록, 101-999호 (예: A301, B402)",
    "students.addSuccess": "학생이 추가되었습니다",
    "students.addDuplicate": "같은 이름과 방의 학생이 이미 있습니다",
    "students.addError": "추가 오류: {{message}}",
    "students.addErrorFallback": "알 수 없는 오류",
    "admin.loginRequiredTitle": "로그인이 필요합니다",
    "admin.loginRequiredBody": "먼저 관리자 권한이 있는 학생으로 로그인한 뒤 관리자 키를 입력하세요.",
    "admin.loginRequiredHint": "보안 정책을 위해 필요합니다.",
    "admin.loginPromptTitle": "관리자",
    "admin.loginPromptBody": "관리자 패널에 접근하려면 관리자 권한이 있는 학생으로 로그인하세요.",
    "admin.panelTitle": "관리자 패널",
    "admin.panelModeSuper": "슈퍼관리자 모드",
    "admin.panelModeAdmin": "관리자 모드",
    "admin.studentsToggleShow": "학생 관리",
    "admin.studentsToggleHide": "학생 숨기기",
    "admin.studentsCount": "학생 ({{count}})",
    "admin.addStudent": "학생 추가",
    "admin.searchPlaceholder": "이름 또는 방으로 검색",
    "admin.filter.all": "전체",
    "admin.filter.registered": "등록",
    "admin.filter.unregistered": "미등록",
    "admin.filter.banned": "차단",
    "admin.roomMissing": "없음",
    "admin.status.registered": "등록됨",
    "admin.status.unregistered": "미등록",
    "admin.status.banned": "차단됨",
    "admin.status.admin": "관리자",
    "admin.status.superAdmin": "슈퍼관리자",
    "admin.status.leader": "리더",
    "admin.editTitle": "학생 수정",
    "admin.resetTitle": "등록을 초기화할까요?",
    "admin.resetConfirm": "{{name}}의 등록을 초기화합니다.",
    "admin.resetHint": "학생은 다시 등록할 수 있습니다.",
    "admin.resetAction": "초기화",
    "admin.banTitle": "학생 차단",
    "admin.banConfirm": "{{name}}을(를) 차단합니다.",
    "admin.banPlaceholder": "차단 사유 (선택)",
    "admin.banAction": "차단",
    "admin.deleteTitle": "학생 삭제?",
    "admin.deleteConfirm": "{{name}}을(를) 삭제할까요?",
    "admin.deleteHint": "이 작업은 되돌릴 수 없습니다. 모든 데이터가 삭제됩니다.",
    "admin.deleteAction": "삭제",
    "admin.addQueueTitle": "대기열에 추가",
    "admin.addQueueStudent": "학생",
    "admin.addQueueDate": "세탁 날짜",
    "admin.addQueueWashCount": "세탁 횟수",
    "admin.addQueueCoupons": "쿠폰",
    "admin.addQueueHint": "추가 시 사용 가능한 쿠폰을 확인합니다.",
    "admin.addQueueAction": "추가",
    "admin.close": "닫기",
    "admin.resetSuccess": "등록이 초기화되었습니다",
    "admin.resetError": "등록 초기화 실패",
    "admin.banSuccess": "학생이 차단되었습니다",
    "admin.unbanSuccess": "차단 해제되었습니다",
    "admin.deleteSuccess": "학생이 삭제되었습니다",
    "admin.addQueueSuccess": "대기열에 추가되었습니다",
    "admin.toggleAdminGranted": "관리자 권한이 부여되었습니다",
    "admin.toggleAdminRevoked": "관리자 권한이 제거되었습니다",
    "admin.error": "오류: {{message}}",
    "admin.actions.manage": "관리",
    "admin.actions.noName": "이름 없음",
    "admin.actions.roomLabel": "방 {{room}}",
    "admin.actions.roomMissing": "방 정보 없음",
    "admin.badge.superAdmin": "슈퍼관리자",
    "admin.badge.admin": "관리자",
    "admin.badge.leader": "리더",
    "admin.badge.registered": "등록됨",
    "admin.badge.banned": "차단됨",
    "admin.section.queue": "대기열",
    "admin.section.account": "계정",
    "admin.section.rights": "접근 권한",
    "admin.section.danger": "위험 구역",
    "admin.action.queueAdd": "대기열 추가",
    "admin.action.editProfile": "프로필 수정",
    "admin.action.resetRegistration": "등록 초기화",
    "admin.action.ban": "차단",
    "admin.action.unban": "차단 해제",
    "admin.action.makeAdmin": "관리자로 지정",
    "admin.action.removeAdmin": "관리자 권한 해제",
    "admin.action.deleteStudent": "학생 삭제",

    "cleanup.title": "청소 결과",
    "cleanup.subtitle": "블록 공지 및 기록",
    "cleanup.toHome": "홈으로",
    "cleanup.empty": "결과가 없습니다.",
    "password.title": "비밀번호 변경",
    "password.current": "현재 비밀번호",
    "password.new": "새 비밀번호",
    "password.confirm": "새 비밀번호 확인",
    "password.placeholderCurrent": "현재 비밀번호 입력",
    "password.placeholderNew": "새 비밀번호 입력",
    "password.placeholderConfirm": "비밀번호 다시 입력",
    "password.minHint": "최소 6자",
    "password.update": "비밀번호 변경",
    "password.updating": "변경 중...",
    "password.errorRequired": "모든 필드를 입력하세요",
    "password.errorMin": "비밀번호는 최소 6자여야 합니다",
    "password.errorMismatch": "비밀번호가 일치하지 않습니다",
    "password.errorSame": "새 비밀번호는 현재 비밀번호와 달라야 합니다",
    "password.errorAuthMissing": "auth_email 누락",
    "password.errorCurrentInvalid": "현재 비밀번호가 올바르지 않습니다",
    "password.errorUpdate": "비밀번호 변경 오류",
    "password.success": "비밀번호가 변경되었습니다",
    "avatar.title": "아바타 스타일 선택",
    "avatar.previewLabel": "아바타 미리보기:",
    "avatar.currentStyleLabel": "스타일:",
    "avatar.save": "저장",
    "avatar.saving": "저장 중...",
    "avatar.random": "랜덤 아바타 선택",
    "avatar.chooseStyle": "스타일 선택:",
    "avatar.saved": "아바타 저장됨!",
    "avatar.saveError": "아바타 저장 실패",
    "avatar.style.avataaars.desc": "머리와 의상이 있는 기본 스타일",
    "avatar.style.lorelei.desc": "여성 아바타",
    "avatar.style.pixel-art.desc": "픽셀 스타일",
    "avatar.style.adventurer.desc": "모험가 스타일",
    "avatar.style.big-ears.desc": "큰 귀 스타일",
    "avatar.style.bottts.desc": "로봇",
    "avatar.style.croodles.desc": "낙서 스타일",
    "avatar.style.micah.desc": "미니멀 스타일",
    "avatar.style.miniavs.desc": "미니 아바타",
    "avatar.style.notionists.desc": "Notion 스타일",
    "avatar.style.personas.desc": "페르소나",
    "avatar.style.thumbs.desc": "Thumbs 스타일",
    "avatar.style.fun-emoji.desc": "재미있는 이모지",
    "queue.searchPlaceholder": "이름 또는 방으로 검색..."
  }
};

const interpolate = (text: string, vars?: Record<string, string | number>) => {
  if (!vars) return text;
  return text.replace(/\{\{(\w+)\}\}/g, (_, key) => String(vars[key] ?? ""));
};

const getInitialLanguage = (): UiLanguage => {
  if (typeof window === "undefined") return "ru";
  const stored = localStorage.getItem("appLanguage") as UiLanguage | null;
  if (stored === "ru" || stored === "en" || stored === "ko") return stored;
  return "ru";
};

const getInitialTheme = (): UiTheme => {
  if (typeof window === "undefined") return "light";
  const stored = localStorage.getItem("appTheme") as UiTheme | null;
  if (stored === "light" || stored === "dark") return stored;
  return "light";
};

export const UiProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<UiLanguage>(getInitialLanguage);
  const [theme, setTheme] = useState<UiTheme>(getInitialTheme);

  useEffect(() => {
    if (typeof window === "undefined") return;
    localStorage.setItem("appLanguage", language);
    document.documentElement.lang = language;
  }, [language]);

  useLayoutEffect(() => {
    if (typeof window === "undefined") return;
    const html = document.documentElement;
    if (theme === "dark") {
      html.classList.add("dark");
    } else {
      html.classList.remove("dark");
    }
    localStorage.setItem("appTheme", theme);
  }, [theme]);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const dict = translations[language] || translations.ru;
      const base = dict[key] || translations.ru[key] || key;
      return interpolate(base, vars);
    },
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      theme,
      setTheme,
      t,
    }),
    [language, theme, t]
  );

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
};

export const useUi = () => {
  const context = useContext(UiContext);
  if (!context) {
    throw new Error("useUi must be used within UiProvider");
  }
  return context;
};

